# Image name
TARGET = fbb_keyboard

# MCU specs (Teensy++ 2.0)
MCU = at90usb1286
F_CPU = 16000000
# Boot Section Size in *bytes*
#   Teensy halfKay   512
#   Teensy++ halfKay 2048
#   Atmel DFU loader 4096
#   LUFA bootloader  4096
OPT_DEFS += -DBOOTLOADER_SIZE=4096

#
UNIMAP_ENABLE = yes
KEYMAP_SECTION_ENABLE = yes

# default values
include Makefile
